In [5]:
import numpy as np

# Zadanie 1: Utwórz jednowymiarową tablicę (wektor) z pierwszymi 10 dodatnimi liczbami całkowitymi i wyświetl jej wartość.

In [7]:
vector_10 = np.arange(1, 11)
print("Zadanie 1:", vector_10)

Zadanie 1: [ 1  2  3  4  5  6  7  8  9 10]


# Zadanie 2: Utwórz dwuwymiarową tablicę (macierz) o rozmiarze 3x3, wypełnij ją zerami i wyświetl jej wartość.


In [8]:
matrix_3x3_zeros = np.zeros((3, 3))
print("\nZadanie 2:\n", matrix_3x3_zeros)


Zadanie 2:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Zadanie 3: Utwórz tablicę o rozmiarze 5x5, wypełnij ją losowymi liczbami całkowitymi z zakresu od 1 do 10 i wyświetl jej wartość.


In [9]:
matrix_5x5_random = np.random.randint(1, 11, size=(5, 5))
print("\nZadanie 3:\n", matrix_5x5_random)


Zadanie 3:
 [[ 3  5  8  4  6]
 [ 9 10  4  9  6]
 [ 7  6  4  5  7]
 [ 9  6  4  8  8]
 [ 7  5  8  3  6]]


# Zadanie 4: Utwórz tablicę o rozmiarze 4x4, wypełnij ją losowymi liczbami rzeczywistymi z zakresu od 0 do 1 i wyświetl jej wartość.


In [10]:
matrix_4x4_random_floats = np.random.rand(4, 4)
print("\nZadanie 4:\n", matrix_4x4_random_floats)


Zadanie 4:
 [[0.46988848 0.77053012 0.24285757 0.15597161]
 [0.76575963 0.57349144 0.43655124 0.03106206]
 [0.28546908 0.14502531 0.29517372 0.89569986]
 [0.4902967  0.53072179 0.46055302 0.42273067]]


In [11]:
# Zadanie 5: Utwórz dwie jednowymiarowe tablice o rozmiarze 5, wypełnij je losowymi liczbami całkowitymi z zakresu od 1 do 10 i wykonaj na nich operacje dodawania, odejmowania i mnożenia.


In [12]:
vector_5_a = np.random.randint(1, 11, size=5)
vector_5_b = np.random.randint(1, 11, size=5)
print("\nZadanie 5:\nvector_5_a:", vector_5_a)
print("vector_5_b:", vector_5_b)
print("Addition:", vector_5_a + vector_5_b)
print("Subtraction:", vector_5_a - vector_5_b)
print("Multiplication:", vector_5_a * vector_5_b)


Zadanie 5:
vector_5_a: [6 8 4 7 7]
vector_5_b: [ 7 10  3 10  8]
Addition: [13 18  7 17 15]
Subtraction: [-1 -2  1 -3 -1]
Multiplication: [42 80 12 70 56]


# Zadanie 6: Utwórz dwa wektory o rozmiarze 7, wypełnij je losowymi liczbami i znajdź ich iloczyn skalarny.


In [13]:
vector_7_a = np.random.random(7)
vector_7_b = np.random.random(7)
dot_product = np.dot(vector_7_a, vector_7_b)
print("\nZadanie 6:\nvector_7_a:", vector_7_a)
print("vector_7_b:", vector_7_b)
print("Dot product:", dot_product)


Zadanie 6:
vector_7_a: [0.33015181 0.32465475 0.39815414 0.64966329 0.71073994 0.18073619
 0.80178021]
vector_7_b: [0.0465633  0.08792086 0.85962417 0.47654472 0.24131325 0.84127618
 0.79649085]
Dot product: 1.6579440209322744


# Zadanie 7: Utwórz dwie macierze o rozmiarach 2x2 i 2x3, wypełnij je losowymi liczbami całkowitymi z zakresu od 1 do 10 i pomnóż je.


In [14]:
matrix_2x2 = np.random.randint(1, 11, size=(2, 2))
matrix_2x3 = np.random.randint(1, 11, size=(2, 3))
matrix_product = np.dot(matrix_2x2, matrix_2x3)
print("\nZadanie 7:\nmatrix_2x2:\n", matrix_2x2)
print("matrix_2x3:\n", matrix_2x3)
print("Product:\n", matrix_product)


Zadanie 7:
matrix_2x2:
 [[ 3 10]
 [ 4  3]]
matrix_2x3:
 [[ 2  5  3]
 [ 3  5 10]]
Product:
 [[ 36  65 109]
 [ 17  35  42]]


# Zadanie 8: Utwórz macierz o rozmiarze 3x3, wypełnij ją losowymi liczbami całkowitymi z zakresu od 1 do 10 i znajdź jej odwrotność.


In [15]:
matrix_3x3 = np.random.randint(1, 11, size=(3, 3))
try:
    matrix_inverse = np.linalg.inv(matrix_3x3)
    print("\nZadanie 8:\nmatrix_3x3:\n", matrix_3x3)
    print("Inverse:\n", matrix_inverse)
except np.linalg.LinAlgError:
    print("\nZadanie 8: Macierz nie jest odwracalna.")


Zadanie 8:
matrix_3x3:
 [[ 2 10  8]
 [10  2  3]
 [ 7  2  7]]
Inverse:
 [[-0.01877934  0.12676056 -0.03286385]
 [ 0.11502347  0.09859155 -0.17370892]
 [-0.01408451 -0.15492958  0.22535211]]


# Zadanie 9: Utwórz macierz 4x4, wypełnij ją losowymi liczbami rzeczywistymi z zakresu od 0 do 1 i przetransponuj ją.


In [16]:
matrix_4x4 = np.random.rand(4, 4)
matrix_transpose = matrix_4x4.T
print("\nZadanie 9:\nmatrix_4x4:\n", matrix_4x4)
print("Transpose:\n", matrix_transpose)


Zadanie 9:
matrix_4x4:
 [[0.3468988  0.67751042 0.83760689 0.45019052]
 [0.93841021 0.96513894 0.19488629 0.71579482]
 [0.80472478 0.88486808 0.83542047 0.19228062]
 [0.795424   0.16454366 0.80720044 0.72660954]]
Transpose:
 [[0.3468988  0.93841021 0.80472478 0.795424  ]
 [0.67751042 0.96513894 0.88486808 0.16454366]
 [0.83760689 0.19488629 0.83542047 0.80720044]
 [0.45019052 0.71579482 0.19228062 0.72660954]]


# Zadanie 10: Utwórz macierz o rozmiarze 3x4 i wektor o rozmiarze 4, wypełnij je losowymi liczbami całkowitymi z zakresu od 1 do 10 i pomnóż macierz przez wektor.


In [17]:
matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
vector_4 = np.random.randint(1, 11, size=4)
matrix_vector_product = np.dot(matrix_3x4, vector_4)
print("\nZadanie 10:\nmatrix_3x4:\n", matrix_3x4)
print("vector_4:", vector_4)
print("Product:", matrix_vector_product)


Zadanie 10:
matrix_3x4:
 [[10  9 10  2]
 [ 8  3  5  8]
 [ 4  2  2  3]]
vector_4: [3 2 6 4]
Product: [116  92  40]


# Zadanie 11: Utwórz macierz o rozmiarze 2x3 i wektor o rozmiarze 3, wypełnij je losowymi liczbami rzeczywistymi z zakresu od 0 do 1 i pomnóż macierz przez wektor.


In [18]:
matrix_2x3 = np.random.rand(2, 3)
vector_3 = np.random.rand(3)
matrix_vector_product_floats = np.dot(matrix_2x3, vector_3)
print("\nZadanie 11:\nmatrix_2x3:\n", matrix_2x3)
print("vector_3:", vector_3)
print("Product:", matrix_vector_product_floats)


Zadanie 11:
matrix_2x3:
 [[0.79171846 0.69777911 0.06749178]
 [0.0039599  0.60356574 0.0439457 ]]
vector_3: [0.57221524 0.06622929 0.8894663 ]
Product: [0.55927844 0.08132787]


# Zadanie 12: Utwórz dwie macierze o rozmiarze 2x2, wypełnij je losowymi liczbami całkowitymi z zakresu od 1 do 10 i wykonaj ich mnożenie pierwiastkowe.


In [19]:
matrix_2x2_a = np.random.randint(1, 11, size=(2, 2))
matrix_2x2_b = np.random.randint(1, 11, size=(2, 2))
elementwise_multiplication = matrix_2x2_a * matrix_2x2_b
print("\nZadanie 12:\nmatrix_2x2_a:\n", matrix_2x2_a)
print("matrix_2x2_b:\n", matrix_2x2_b)
print("Element-wise multiplication:\n", elementwise_multiplication)


Zadanie 12:
matrix_2x2_a:
 [[8 9]
 [9 5]]
matrix_2x2_b:
 [[1 6]
 [1 3]]
Element-wise multiplication:
 [[ 8 54]
 [ 9 15]]


# Zadanie 13: Utwórz dwie macierze o rozmiarze 2x2, wypełnij je losowymi liczbami całkowitymi z zakresu od 1 do 10 i znajdź ich iloczyn.


In [20]:
matrix_2x2_c = np.random.randint(1, 11, size=(2, 2))
matrix_2x2_d = np.random.randint(1, 11, size=(2, 2))
matrix_product_cd = np.dot(matrix_2x2_c, matrix_2x2_d)
print("\nZadanie 13:\nmatrix_2x2_c:\n", matrix_2x2_c)
print("matrix_2x2_d:\n", matrix_2x2_d)
print("Product:\n", matrix_product_cd)


Zadanie 13:
matrix_2x2_c:
 [[1 3]
 [7 8]]
matrix_2x2_d:
 [[3 5]
 [5 6]]
Product:
 [[18 23]
 [61 83]]


# Zadanie 14: Utwórz macierz 5x5, wypełnij ją losowymi liczbami całkowitymi z zakresu od 1 do 100 i znajdź sumę elementów macierzy.


In [21]:
matrix_5x5_large = np.random.randint(1, 101, size=(5, 5))
matrix_sum = np.sum(matrix_5x5_large)
print("\nZadanie 14:\nmatrix_5x5_large:\n", matrix_5x5_large)
print("Sum of elements:", matrix_sum)


Zadanie 14:
matrix_5x5_large:
 [[41 13 34 73 31]
 [61 21 75 18 52]
 [37 92 47 96 30]
 [13 91  4 45 71]
 [38 62  1 26 39]]
Sum of elements: 1111


# Zadanie 15: Utwórz dwie macierze o rozmiarze 4x4, wypełnij je losowymi liczbami całkowitymi z zakresu od 1 do 10 i znajdź ich różnicę.


In [22]:
matrix_4x4_e = np.random.randint(1, 11, size=(4, 4))
matrix_4x4_f = np.random.randint(1, 11, size=(4, 4))
matrix_difference = matrix_4x4_e - matrix_4x4_f
print("\nZadanie 15:\nmatrix_4x4_e:\n", matrix_4x4_e)
print("matrix_4x4_f:\n", matrix_4x4_f)
print("Difference:\n", matrix_difference)


Zadanie 15:
matrix_4x4_e:
 [[ 7  1  7  4]
 [ 1  1  7 10]
 [ 8  8  4  6]
 [ 1  4  6  3]]
matrix_4x4_f:
 [[ 5  6 10  6]
 [ 8  2 10 10]
 [10  5  5  6]
 [ 7  1  8 10]]
Difference:
 [[ 2 -5 -3 -2]
 [-7 -1 -3  0]
 [-2  3 -1  0]
 [-6  3 -2 -7]]


# Zadanie 16: Utwórz macierz 3x3, wypełnij ją losowymi liczbami rzeczywistymi z zakresu od 0 do 1 i znajdź wektor kolumnowy zawierający sumę elementów każdego wiersza macierzy.


In [23]:
matrix_3x3_floats = np.random.rand(3, 3)
row_sums = np.sum(matrix_3x3_floats, axis=1)
print("\nZadanie 16:\nmatrix_3x3_floats:\n", matrix_3x3_floats)
print("Row sums:", row_sums)


Zadanie 16:
matrix_3x3_floats:
 [[0.77039272 0.7716718  0.04308714]
 [0.67664122 0.7335512  0.82267152]
 [0.70830804 0.68015939 0.64357495]]
Row sums: [1.58515166 2.23286394 2.03204238]


# Zadanie 17: Utwórz macierz o rozmiarze 3x4 z dowolnymi liczbami całkowitymi i utwórz macierz z kwadratami tych liczb.


In [24]:
matrix_3x4_any = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_squared = np.square(matrix_3x4_any)
print("\nZadanie 17:\nmatrix_3x4_any:\n", matrix_3x4_any)
print("Squared matrix:\n", matrix_squared)



Zadanie 17:
matrix_3x4_any:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Squared matrix:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


# Zadanie 18: Utwórz wektor o rozmiarze 4, wypełnij go losowymi liczbami całkowitymi z zakresu od 1 do 50 i znajdź wektor pierwiastków kwadratowych z tych liczb.


In [25]:
vector_4_large = np.random.randint(1, 51, size=4)
vector_sqrt = np.sqrt(vector_4_large)
print("\nZadanie 18:\nvector_4_large:", vector_4_large)
print("Square roots:", vector_sqrt)


Zadanie 18:
vector_4_large: [34 48 43 48]
Square roots: [5.83095189 6.92820323 6.55743852 6.92820323]
